services:
  mysql:
    image: mysql:latest
    container_name: "mysql_"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: complexstring
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  wordpress:
    image: wordpress:latest
    container_name: "wordpress_"
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    ports:
      - 3000:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin_"
    depends_on:
      - mysql
    ports:
      - 3001:80
    environment:
      PMA_HOSTS: mysql
      #PMA_USER: user
      #PMA_PASSWORD: password
